[package]
name = "cp-swap-state"
version = "0.1.0"
description = "Lightweight account library"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "cp_swap_state"

[dependencies]
anchor-lang = "0.29.0"
